name: Scala CI

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'release version'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: test  "${{ github.ref }}" = "refs/heads/master" ||  echo "Release can be created only from master (${{ github.ref }} not supported)." && false
    - name: set version
      run: |
        export VERSION=$(echo ${{ github.event.inputs.releaseVersion }} | sed 's/v//')
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
        echo "VRELEASE_VERSION=v$VERSION" >> $GITHUB_ENV
    - name: release sbt
      run: |
        git config --local user.email "izanami-github-actions@users.noreply.github.com"
        git config --local user.name "izanami-github-actions"
        sbt "release with-defaults release-version ${{ env.RELEASE_VERSION }}"
    - name: switch to tag
      run: git checkout tags/${{ env.VRELEASE_VERSION }}
