name: Scala CI

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'release version'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: release sbt
      run: |
        git config --local user.email "izanami-github-actions@users.noreply.github.com"
        git config --local user.name "izanami-github-actions"
        sbt "release with-defaults release-version ${{ github.event.inputs.releaseVersion }}"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: "v${{ github.event.inputs.releaseVersion }}"
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
    - name: switch to tag
      run: git checkout tags/v${{ github.event.inputs.releaseVersion }}
